# Generated by Django 5.2.13 on 2026-08-02 06:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(help_text='Proposed max length default (ISP-001 §6) - not specified in DBD-001/BRR-001; see FS-001 Open Question #3.', max_length=100)),
                ('active', models.BooleanField(default=True, help_text='Soft-delete flag (DBD-001 §5) - no hard deletes in this schema.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['brand_name'],
                'indexes': [models.Index(fields=['brand_name'], name='idx_brands_brand_name')],
            },
        ),
    ]
