# Generated by Django 5.2.13 on 2026-08-02 06:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_master', '0001_create_brands'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(help_text='Roots the Variant list for this Model (DDD-001 §3).', on_delete=django.db.models.deletion.RESTRICT, related_name='models', to='vehicle_master.brand')),
            ],
            options={
                'db_table': 'models',
                'ordering': ['model_name'],
                'indexes': [models.Index(fields=['brand'], name='idx_models_brand_id'), models.Index(fields=['brand', 'model_name'], name='idx_models_brand_model_name')],
            },
        ),
    ]
