# Generated by Django 5.2.13 on 2026-08-02 06:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_master', '0002_create_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(help_text='Roots the ValuationMaster rows priced against this Variant.', on_delete=django.db.models.deletion.RESTRICT, related_name='variants', to='vehicle_master.model')),
            ],
            options={
                'db_table': 'variants',
                'ordering': ['variant_name'],
                'indexes': [models.Index(fields=['model'], name='idx_variants_model_id'), models.Index(fields=['model', 'variant_name'], name='idx_variants_model_var_name')],
            },
        ),
    ]
