# Generated by Django 5.2.13 on 2026-08-02 06:10

import django.db.models.deletion
import uuid
import vehicle_master.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_master', '0003_create_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationMaster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField(validators=[vehicle_master.validators.validate_year_range])),
                ('minimum_selling_price', models.DecimalField(decimal_places=2, help_text='MSP - proposed precision default (max_digits/decimal_places not specified in DBD-001).', max_digits=12, validators=[vehicle_master.validators.validate_non_negative_amount])),
                ('margin', models.DecimalField(decimal_places=2, max_digits=12, validators=[vehicle_master.validators.validate_non_negative_amount])),
                ('scrap_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[vehicle_master.validators.validate_non_negative_amount])),
                ('active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='valuation_master_versions', to='vehicle_master.variant')),
            ],
            options={
                'db_table': 'valuation_master',
                'ordering': ['-effective_from'],
                'indexes': [models.Index(fields=['active'], name='idx_valmaster_active')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('year', 'variant'), name='uniq_active_valmaster_year_variant'), models.CheckConstraint(condition=models.Q(('minimum_selling_price__gte', 0)), name='chk_valmaster_msp_non_negative'), models.CheckConstraint(condition=models.Q(('margin__gte', 0)), name='chk_valmaster_margin_non_negative'), models.CheckConstraint(condition=models.Q(('scrap_value__gte', 0)), name='chk_valmaster_scrap_non_negative')],
            },
        ),
    ]
